### ISSUE TITLE
Login: english error message

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#187]
Login error "Incorrect username or password" should be in German.

**Comment by nadar** [comment]
@martinpetrasch  `admin\models\LoginForm` could you also changed (translate) the error messages in `admin\models\User`

**Comment by nadar** [comment]
Martin du musst auch die attributeLabels() setzten, ansonsten stehen die Felder auf englisch! @rolandschaub sonst noch Anmerkungen?

**Comment by martinpetrasch** [comment]
@nadar ist bei mir alles Deutsch, hast du ein Beispiel wo noch etwas auf Englisch steht?

**Comment by nadar** [comment]
Die Feldnamen ... Password zbsp. frag @rolandschaub

**Comment by martinpetrasch** [comment]
![image](https://cloud.githubusercontent.com/assets/6354795/8495360/5443a44e-216d-11e5-94be-372ab5c9f094.png)

**Comment by nadar** [comment]
Klick jetzt leer auf Einloggen

**Comment by martinpetrasch** [comment]
![bildschirmfoto 2015-07-03 um 10 26 53](https://cloud.githubusercontent.com/assets/6354795/8495457/0e16e674-216e-11e5-963d-c1d35810941d.png)

**Comment by nadar** [comment]
"Password"
