### ISSUE TITLE
Title to path segment

### ISSUE THREAD

**Issue by TheMaaarc** [zephir/luya#191]
Convert **ü**, **ö** and **ä** to **ue**, **oe** and **ae**.

**Comment by nadar** [comment]
Wo passiert das?

**Comment by TheMaaarc** [comment]
![bildschirmfoto 2015-07-02 um 09 31 57](https://cloud.githubusercontent.com/assets/3450438/8471945/42cbd8e2-209d-11e5-9433-c283c106f2c9.png)

**Comment by nadar** [comment]
request slug behavior: https://github.com/paulsmith/angular-slugify
