### ISSUE TITLE
Reduce folder load time on imageArray

### ISSUE THREAD

**Issue by TheMaaarc** [zephir/luya#260]
![image](https://cloud.githubusercontent.com/assets/3450438/8594447/fea253ea-2640-11e5-9f8d-acf1f289c1db.png)

**Comment by nadar** [comment]
@TheMaaarc Ich kanns leider nicht wirklich reproduzieren. Im Screenshot müssten die Requests sein und nicht die Response des einzelnen (oder wenn, dann der Request Header). Hast du eine Idee welcher Request das war?

**Comment by nadar** [comment]
@TheMaaarc Entschuldigung, jetzt habe ich gefunden was wir gemeint haben.
```
Remote Address:[::1]:80
Request URL:http://localhost/luya/envs/dev/public_html/admin/api-admin-storage/get-folders
Request Method:GET
Status Code:200 OK
```
