### ISSUE TITLE
display config values when hovering over luya version

### ISSUE THREAD

**Issue by nadar** [zephir/luya#272]
When hovering over the luya version in the admin module we should display informations:

- YII_DEBUG
- YII_ENV
- errorHandler: $transferException
- $config id
- timezone
- registered components
- registered assets

**Comment by nadar** [comment]
- add styles to debug toolbar, like useronline.

**Comment by hwernze** [comment]
https://github.com/zephir/luya/commit/6215cf5081ef9832bcaa42d4b627dc871cb161eb
