### ISSUE TITLE
checkboxRelation plugin shows redundant information

### ISSUE THREAD

**Issue by martinpetrasch** [zephir/luya#315]

**Comment by nadar** [comment]
add possibility to set values array, sprintf

**Comment by nadar** [comment]
https://github.com/zephir/luya/commit/105035cca80b95a8fecb41ddc5553443eb709efa

**Comment by nadar** [comment]
https://github.com/zephir/luya/commit/63cd4508425b7fc20153313b2db0ae95eb0ab43b
