### ISSUE TITLE
when using i18n in combination with a referencing selectClass you get a JSON instead of a readable string

### ISSUE THREAD

**Issue by martinpetrasch** [zephir/luya#327]
i.e. newsadmin:
1. create category with two languages
2. create article and select category 
3. in CRUD list view you'll see JSON instead of a title in the default language('de')

![bildschirmfoto 2015-08-07 um 15 47 09](https://cloud.githubusercontent.com/assets/6354795/9137068/98b119b2-3d1b-11e5-975e-83278bfdcfaa.png)

**Comment by martinpetrasch** [comment]
this issue also effects frontend views when echoing the i18n vars

**Comment by nadar** [comment]
@martinpetrasch The frontend should not be affected if you are NOT using `asArray()`.
