### ISSUE TITLE
ngRest Image

### ISSUE THREAD

**Issue by nadar** [zephir/luya#342]
+ i18n image plugin does not keep image id (lost after reload)
+ Missing translation titles (Deutsch, English)

**Comment by nadar** [comment]
Multilingual Titles (hide if i18n true, like in the other zaa)

**Comment by TheMaaarc** [comment]
@nadar Das wurde ja mit issue #532 geschlossen oder sind dir noch weitere Probleme diesbezüglich aufgefallen?
