### ISSUE TITLE
Rework site tree in page editor.

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#363]
Optimize and extend the site tree in the left-hand pane of the page editor:

- make it more compact (smaller font? less line-spacing?)
- make nodes expandable/collapsible
- store state per user (what nodes were expanded/collapsed)
- use different Icons depending on page type (e.g. page, internal redirection, external redirection)
- distinct (via color or icon) between states "inactive" and "hidden in navigation"

**Comment by rolandschaub** [comment]
Very good points, Roland!

**Comment by rolandschaub** [comment]
Thank you, Roland.

**Comment by rolandschaub** [comment]
No problem, you are welcome.

**Comment by rolandschaub** [comment]
So are you.

**Comment by rolandschaub** [comment]
Great, thanks.

**Comment by TheMaaarc** [comment]
E-Mail spaaaam.

**Comment by nadar** [comment]
Thank you, @rolandschaub! Very good points @rolandschaub!

**Comment by rolandschaub** [comment]
Gäll.
