### ISSUE TITLE
CMS-Property access to methods

### ISSUE THREAD

**Issue by martinpetrasch** [zephir/luya#399]
Example: If I want to use ids in properties instead of values, I want to be able to get the actual value in frontend

**Comment by martinpetrasch** [comment]
Maybe it's more correct to add a method access to properties via frontend instead of changing it completely, because you still want to access values.

**Comment by nadar** [comment]
@martinpetrasch see https://luya.io/de/dokumentation/app-cmsproperties?cache=1#eventbeforefind
