### ISSUE TITLE
Add new icon URL to icon() function in Block class in Block Builder.

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#414]
Replace
http://web.archive.org/web/20150315064340/http://materializecss.com/icons.html
with
https://www.google.com/design/icons/

**Comment by rolandschaub** [comment]
Gäll.

**Comment by nadar** [comment]
@rolandschaub thank you!

**Comment by rolandschaub** [comment]
Bitte, bitte, nichts zu danken.
