### ISSUE TITLE
More compact page controls

### ISSUE THREAD

**Issue by nadar** [zephir/luya#415]
Make the nav (page) controls more compact for smaller screen size

+ styling of "Eigenschaften" Button (icon only?)
+ removing cat switcher (add ability to move tree view instead)?

<img width="1208" alt="bildschirmfoto 2015-10-27 um 22 24 31" src="https://cloud.githubusercontent.com/assets/3417221/10773102/cdf94e0a-7cf9-11e5-945c-e6477f0f166b.png">

**Comment by TheMaaarc** [comment]
![image](https://cloud.githubusercontent.com/assets/3450438/10913566/c10d8c74-824e-11e5-8841-faa4e3d0ffe9.png)

**Comment by TheMaaarc** [comment]
![image](https://cloud.githubusercontent.com/assets/3450438/10913588/d8cb783a-824e-11e5-9010-971304420231.png)
