### ISSUE TITLE
Events: Date/Time fields with optional input

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#421]
Date/time fields "Anzeigen von" and "Anzeigen bis" have to be optional (storing a NULL in the database when empty). This is also a requirement for other models with optional date and/or time fields. See screenshot.
![a6fd434a-7d5f-11e5-9998-d7560c3b4241](https://cloud.githubusercontent.com/assets/3786245/10793810/bf78362c-7d92-11e5-9976-dbde96193050.png)

**Comment by rolandschaub** [comment]
Are you satisfied now, @nadar?

**Comment by nadar** [comment]
am i @rolandschaub?

**Comment by rolandschaub** [comment]
Hallo @nadar, ich wäre froh, wenn diese Anpassung bald gemacht werden könnte.
