### ISSUE TITLE
Enable default route without parameters in Module class of module.

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#422]
Url::toModuleRoute('event', ''); should return default link (e.g. list view of Events module).

Module.php:

public $urlRules = [
        ['pattern' => 'event/<id:\d+>/<slug:[a-zA-Z0-9\-]+>', 'route' => 'event/detail/index'],
        ['pattern' => 'event', 'route' => 'event/default/index'],
    ];

**Comment by nadar** [comment]
not a bug
