### ISSUE TITLE
CMS Admin: Make page edit more compact

### ISSUE THREAD

**Issue by nadar** [zephir/luya#458]
We have to make the CMS Page-Edit header (togglers, categorie chooser, etc.) more compact:
- Styling of property button
- Smaller font in on/off, show/hide toggler?

<img width="1166" alt="bildschirmfoto 2015-11-02 um 18 35 32" src="https://cloud.githubusercontent.com/assets/3417221/10889150/8cc437ba-8190-11e5-9f92-7ccb0d47b835.png">

**Comment by TheMaaarc** [comment]
Duplicated #415 ?

**Comment by nadar** [comment]
@TheMaaarc agree
