### ISSUE TITLE
CMS Admin: Block form padding

### ISSUE THREAD

**Issue by nadar** [zephir/luya#459]
The form paddings seems to be different then in crud:

<img width="1114" alt="bildschirmfoto 2015-11-02 um 18 53 25" src="https://cloud.githubusercontent.com/assets/3417221/10889579/1e7491da-8193-11e5-8356-d896717aea85.png">

**Comment by TheMaaarc** [comment]
Already closed with commit https://github.com/zephir/luya/commit/70df4bff21b35dba1249d3b56dbc840aa802f958
