### ISSUE TITLE
CMS Admin: Block cfgs edit form toggler

### ISSUE THREAD

**Issue by nadar** [zephir/luya#460]
As of removing the materialize accordion(?), we have to provide a custom function to enable the cfgs toggler. Make the cfgs button and form more beautiful (smooth button to toggle cfgs?)

@TheMaaarc use ng-show, otherwise just make the styling and i will enable the functionality.

<img width="1146" alt="bildschirmfoto 2015-11-02 um 18 55 45" src="https://cloud.githubusercontent.com/assets/3417221/10889617/5a3f04d4-8193-11e5-8933-507669be859c.png">

PS: Screenshot taken from table block.

**Comment by TheMaaarc** [comment]
@nadar Not functional now (always closed).

Onclick, change variable to true:
```
<div class="block__configs-toggler btn btn--small grey lighten-3 black-text z-depth-0"><i class="material-icons">settings</i> Einstellungen <span class="block__configs-closetext">schliessen</span></div>
```

Add class `block__configs--open` to `block__configs`. Already prepared that:
```
<div class="block__configs" ng-class="{'block__configs--open': configIsOpen}">
```
