### ISSUE TITLE
CMS Admin: Sidetree, same visual hover effect as in blocks

### ISSUE THREAD

**Issue by nadar** [zephir/luya#474]
Use the same styles for "moving pages" as when "moving blocks" (the green line, instead of the blue dotted box). Avoid making the tree bigger when move is enabled.

![image](https://cloud.githubusercontent.com/assets/3417221/10939482/32135634-8302-11e5-9678-35a7fc296c5f.png)

**Comment by TheMaaarc** [comment]
![luya-treeview-problem](https://cloud.githubusercontent.com/assets/3450438/10945946/163bbf96-8320-11e5-98b4-228b1203df98.gif)

**Comment by TheMaaarc** [comment]
New treeview layout solves this problem.
