### ISSUE TITLE
Missing jQuery for the mobile main navigation

### ISSUE THREAD

**Issue by hwernze** [zephir/luya#485]
Button for mobil nav is there but no side menu appears

**Comment by nadar** [comment]
@hwernze screenshot please. thanks

**Comment by TheMaaarc** [comment]
@hwernze Screenshot is not necessary.

**Comment by hwernze** [comment]
thx

**Comment by hwernze** [comment]
![bildschirmfoto 2015-11-06 um 11 22 03](https://cloud.githubusercontent.com/assets/8361779/10994787/ca157b98-8478-11e5-8f69-128942e5af7d.png)
Just in case ;)

**Comment by hwernze** [comment]
Mobil-Nav do not collapsing-behavior still incorrect. Clicking nav icon or even nav items always lead to the luya-home screen.
