### ISSUE TITLE
New page redirection type

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#493]
Create a new page redirection type: redirect to first child page (often needed when a parent page has no content and should instead forward to its first child page).

**Comment by nadar** [comment]
I don't think this is a type, its just a casual redirection to your selected page.

**Comment by rolandschaub** [comment]
It *is* a type: It doesn't redirect to a specific page but to the first child, which can change when new child pages are added or when their order is changed.

**Comment by nadar** [comment]
@martinpetrasch What do you think?

**Comment by martinpetrasch** [comment]
I think we should set a specific page for the redirect but if we really need the automatic redirect feature - we can integrate it, but then we've just another option.
