### ISSUE TITLE
Remove icon next to "Einstellungen"

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#494]
The cogwheel icon next to "Einstellungen" is confusing as it looks like a (separate) button:

<img width="854" alt="einstellungen" src="https://cloud.githubusercontent.com/assets/3786245/11031787/28aee27e-86d7-11e5-9d0b-ba5383014129.png">

Better remove it.

**Comment by nadar** [comment]
@rolandschaub i agree. What do you think @TheMaaarc? If you agree too, assign the issue to @hwernze.

**Comment by TheMaaarc** [comment]
I don't think it's confusing. Maybe we should make it clickable? Without the icon, the settings box has to be 100% width again, otherwise it would look really stupid.

@hwernze For now, make the gear icon clickable.

**Comment by rolandschaub** [comment]
Standing outside the grey area it looks like a separate feature and therefore is confusing in my opinion. Just by looking at the two elements it is not clear whether they belong together or not. It makes not much difference if the icon is clickable.
