### ISSUE TITLE
Show target path for redirected pages in admin

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#508]
Add redirection path to info "Diese Seite ist ein Redirect", like "Diese Seite ist eine Umleitung auf /besuch/informationen":

![redirect](https://cloud.githubusercontent.com/assets/3786245/11064545/2063207a-87be-11e5-881d-295382a92fc1.png)

**Comment by rolandschaub** [comment]
Maybe even make the path an active link that loads the target page in the administration.

**Comment by nadar** [comment]
@martinpetrasch i don't think this output is an expected behavior?

![image](https://cloud.githubusercontent.com/assets/3417221/11090318/3b2cf026-8871-11e5-9596-acf997eb572e.png)
