### ISSUE TITLE
Improve video block (add Vimeo and make responsive work)

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#509]
- make video element work with YouTube and Vimeo URLs
- add hint that it works for YouTube and Vimeo URLs (e.g. as part of label or below URL field)
- make "Controls ausblenden" a checkbox (always preferred if only yes/no selection)
- make it responsive (doesn't seem to be the case)

![video-element](https://cloud.githubusercontent.com/assets/3786245/11064897/658abff8-87c0-11e5-8580-5258f1d155e8.png)

**Comment by martinpetrasch** [comment]
@nadar please close issue (closed with 9d3a15a09dbcae7a4de7270ed80bb7c8cc1070c3)

**Comment by nadar** [comment]
@martinpetrasch please update the changelog to close this issue. thanks
