### ISSUE TITLE
Misleading icon for current date

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#514]
The icon to set the current date is misleading: it looks like opening a date selector. Better use a text link "Aktuelles Datum setzen".

<img width="81" alt="current date icon" src="https://cloud.githubusercontent.com/assets/3786245/11088090/e5d6561e-885f-11e5-8b3e-5513c88d93b5.png">

**Comment by nadar** [comment]
@rolandschaub any idea? https://www.google.com/design/icons/

**Comment by nadar** [comment]
@rolandschaub "Aktuelles Datum setzen" Will result in a large ugly looking button....

**Comment by rolandschaub** [comment]
That's why I wrote "Text link". Can be in grey. I don't think there's an icon clear enough for this function.
