### ISSUE TITLE
More vertical space above/below checkbox list

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#516]
Add vertical space (+ 5-10 pixels) above and below checkbox lists. Otherwise it is harder to distinguish between checkboxes of different adjoining lists:

<img width="455" alt="checkbox lists" src="https://cloud.githubusercontent.com/assets/3786245/11088275/465f8e14-8861-11e5-85af-2c2ac8e971f8.png">

**Comment by nadar** [comment]
@rolandschaub All form fields does have the same padding/spacing on bottom/top. I don't think we can change it only for checkboxes, otherwhise we heave to increase the margin top/bottom globally. What do you think @TheMaaarc?

**Comment by TheMaaarc** [comment]
Each form type has a custom class, so i can change the margin only on checkbox lists.

**Comment by nadar** [comment]
ok, but i don't think its a good practice to change the margin only for a custom field.

**Comment by rolandschaub** [comment]
I don't think it is bad if it improves usability.

**Comment by nadar** [comment]
@rolandschaub we are not going to change the margin for a specific field.

**Comment by rolandschaub** [comment]
Okay.
