### ISSUE TITLE
File manager: Move function buttons for selection

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#535]
When selecting one or more files in the file manager, the function buttons that appear above the file list should be positioned further up so that the list doesn't move down.

Current layout:

<img width="762" alt="selected files functions now" src="https://cloud.githubusercontent.com/assets/3786245/11116991/87485444-8936-11e5-9e30-61d50df9193e.png">

Optimized:

<img width="771" alt="selected files functions optimized" src="https://cloud.githubusercontent.com/assets/3786245/11116996/8fcda4a2-8936-11e5-8e64-a140607a54d9.png">

**Comment by TheMaaarc** [comment]
Button styling siehe: https://luya.io/app-admin-styles#buttons
