### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by TheMaaarc** [zephir/luya#552]
Test luya in newest Safari Browser and fix the biggest problems.

![bildschirmfoto 2015-11-16 um 15 57 54](https://cloud.githubusercontent.com/assets/3450438/11235852/4d6ab066-8dd5-11e5-8367-9cd973214baa.png)
![bildschirmfoto 2015-11-16 um 15 58 43](https://cloud.githubusercontent.com/assets/3450438/11235850/4d679188-8dd5-11e5-8e45-2e81f9e40c40.png)
![bildschirmfoto 2015-11-16 um 15 58 13](https://cloud.githubusercontent.com/assets/3450438/11235851/4d6a1b60-8dd5-11e5-9154-936a66aa2ce9.png)

**Comment by hwernze** [comment]
Wich version is the client using & what is required for angular?

**Comment by nadar** [comment]
https://docs.angularjs.org/misc/faq

from the angularjs.org faq:

> What browsers does Angular work with?
We run our extensive test suite against the following browsers: the latest versions of Chrome, Firefox, Safari, and Safari for iOs, as well as Internet Explorer versions 9-11. See Internet Explorer Compatibility for more details on supporting legacy IE browsers.

> If a browser is untested, it doesn't mean it won't work; for example, older Android (2.3.x) is supported in the sense that we avoid the dot notation for reserved words as property names, but we don't actively test changes against it. You can also expect browsers to work that share a large part of their codebase with a browser we test, such as Opera > version 12 (uses the Blink engine), or the various Firefox derivatives.
