### ISSUE TITLE
Add an additional info text to block fields (vars and cfgs)

### ISSUE THREAD

**Issue by martinpetrasch** [zephir/luya#559]
![bildschirmfoto 2015-11-20 um 13 07 26](https://cloud.githubusercontent.com/assets/6354795/11299654/cc3101e8-8f88-11e5-956c-7487be951df6.png)

**Comment by nadar** [comment]
should we add an extra method like

```
getInfo()
{
return [
    "field" => "Optional Info Data";
];
}
```

or add another property inside the array where we defined type and var?

```
['var' => 'field', 'type' => 'zaa-text', 'info' => 'Optional Info Data']
```

**Comment by nadar** [comment]
added method:

```
public function getFieldHelp()
{
    return [
        'varOrCfgName' => 'Hello i am your additional helper text!',
    ];
}
```
