### ISSUE TITLE
Incorrect hint for missing redirects

### ISSUE THREAD

**Issue by hwernze** [zephir/luya#602]
When you create a site as a redirect to an internal site and you don`t select a link the hint is "Value darf nicht leer sein". Better would be telling the name of the missing value or/and highlighting the missing selection.

**Comment by nadar** [comment]
@martinpetrasch  Add `attributeLabels()` informations to Models to returns better erorr messages

+ cmsadmin\models\NavItem
+ cmsadmin\models\NavItemPage
+ cmsadmin\models\NavItemRedirect (This returns the message mentioned from above)
+ cmsadmin\models\NaviItemModule
