### ISSUE TITLE
First run. PHP notice. Whats wrong?

### ISSUE THREAD

**Issue by Emericanec** [zephir/luya#615]
![2015-12-02 22 45 44](https://cloud.githubusercontent.com/assets/7316100/11540482/0b8f626c-993e-11e5-9e85-7f98d3ed6a31.png)

I did everything according to instructions - https://luya.io/en/guide/install

**Comment by nadar** [comment]
Hi
1. Have you run the console commands? `./vendor/bin/luya migrate` `./vendor/bin/luya import` `./vendor/bin/luya setup`
2. Can you login to your Administration area? `yourdomain.com/admin` / `http://localhost/luya-kickstarter/admin`
3. The errors means, that you have not yet set a Homepage/Default Page. (The Exception is improved in the next beta2 release.) So if you can login to your administration area (with your credentials you have provided during the setup process), create a page and click the "is home" icon.

If you do have further problems, let me know.

**Comment by Emericanec** [comment]
1) yes
![2015-12-03 9 26 31](https://cloud.githubusercontent.com/assets/7316100/11552614/932fe332-9997-11e5-82c4-5097e7961448.png)

2) yes
![2015-12-03 9 28 50](https://cloud.githubusercontent.com/assets/7316100/11552640/edf8d5f8-9997-11e5-9c03-cd663f6d4156.png)

3) so empty sidebar. it should be?
![2015-12-03 9 56 23](https://cloud.githubusercontent.com/assets/7316100/11553019/b986a5e4-999b-11e5-8995-844a7c96c5b8.png)

**Comment by nadar** [comment]
@Emericanec yes, this looks good! Now click on "Gruppen" -> "Berechtigungen". An overlay will popup where you can select "Alle markieren", scroll to the bottom and click "Speichern". Now your group (where you are in) does have all privileges and now you will see all modules.

btw. we are going the deliver translations for the administration area in the next release! So you could help us translate everything in your native language, if you like to!

**Comment by Emericanec** [comment]
Done! You can close the task.
![2015-12-03 12 29 48](https://cloud.githubusercontent.com/assets/7316100/11555415/2c03795c-99b1-11e5-86a2-a8682a5bf174.png)
![2015-12-03 12 29 59](https://cloud.githubusercontent.com/assets/7316100/11555414/2c0095a2-99b1-11e5-9b44-cc4bf04376ec.png)

Yes, I'm going to be contributor. I are pleased to help with the translation into Russian.

**Comment by Emericanec** [comment]
Maybe should turn on default main page?

**Comment by nadar** [comment]
good point! creating a default page when running the setup command. You could create a new issue for this?
