### ISSUE TITLE
CMS LIVE iframe preview

### ISSUE THREAD

**Issue by nadar** [zephir/luya#713]

**Comment by nadar** [comment]
https://github.com/zephir/luya/commit/d9c9f90f09b9f273b549621c97d685021bac7754

**Comment by nadar** [comment]
http://plnkr.co/edit/Zi2f0EPxmtEUmdoFR63B?p=preview

**Comment by nadar** [comment]
https://github.com/zephir/luya/commit/5bb55c22acbcfa5128482dcb44d32decbdbdaa01

**Comment by TheMaaarc** [comment]
![image](https://cloud.githubusercontent.com/assets/3450438/12820515/acfd0e1c-cb5f-11e5-8421-0333836bee10.png)

**Comment by nadar** [comment]
+ cursor
+ remove padding-margin
+ remove round corners
+ make border less darker

**Comment by TheMaaarc** [comment]
If you move the AutoPreview, the left container cannot resize to 100% width after disabling, because the js doesen't remove the calculated inline width.

![image](https://cloud.githubusercontent.com/assets/3450438/12849546/6f785efe-cc20-11e5-8b18-9ffcd91d86ab.png)
