### ISSUE TITLE
Empty block problem

### ISSUE THREAD

**Issue by TheMaaarc** [zephir/luya#719]
After moving a block into a subcontainer, an empty block stays at the place where the block was before.
  
Image: Moved the Image block into the Container ("Kopfbegrenzung für Einzelbilder").
![image](https://cloud.githubusercontent.com/assets/3450438/12320430/0271f802-baa9-11e5-99e3-cbc54d20b5e6.png)

**Comment by nadar** [comment]
remove min-height from inline style and add to element
