### ISSUE TITLE
Make search filter in list view sticky

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#722]
When using the search field to filter records, the filter is reset after editing and saving a record. The search should remain sticky, so that the search results are still displayed after editing a record.

![list_view](https://cloud.githubusercontent.com/assets/3786245/12322413/44597974-bab4-11e5-9901-4f963a51878b.png)

**Comment by nadar** [comment]
<img width="1040" alt="bildschirmfoto 2016-02-03 um 20 46 57" src="https://cloud.githubusercontent.com/assets/3417221/12794840/617fd486-cab7-11e5-80cd-a787bcb5811d.png">
