### ISSUE TITLE
Treeview refresh on site load

### ISSUE THREAD

**Issue by TheMaaarc** [zephir/luya#739]
If you click a site in the treeview, the treeview will close. I think because it reloads its data.

**Comment by nadar** [comment]
I was unable to reproduce this bug. What i did:

+ added sub pages
+ added sub sub pages
+ opened the tree for the sub sub page, click on it. click on other pages - no reload

**Comment by nadar** [comment]
this appears when the cmsPageBlock directive is in use in one of those blocks, cause it forces a reload of the menu.
